spring:
  datasource:
    url: jdbc:mysql://localhost:3306/performance_keeper_db?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MySQL_Username}
    password: ${MySQL_Password}
  jpa:
    hibernate:
      ddl-auto: update

  thymeleaf:
    prefix: classpath:/templates/

jwt:
  secret: ${JWT_SECRET}
  token:
    access-token-valid-time: ${access_token_valid_time}
    refresh-token-valid-time: ${refresh_token_valid_time}